guest-agent:
  image: albinodrought/ovirt-guest-agent-centos:latest
  privileged: true
  labels:
    io.rancher.os.scope: system
    io.rancher.os.after: console
  stdin_open: true
  pid: host
  ipc: host
  net: host
  uts: host
  volumes:
    - /dev/virtio-ports:/dev/virtio-ports
  restart: always
