version: '2'
services:
  guest-agent:
    privileged: true
    image: albinodrought/ovirt-guest-agent-centos
    stdin_open: true
    network_mode: host
    volumes:
    - /dev/virtio-ports/com.redhat.spice.0:/dev/virtio-ports/com.redhat.spice.0
    - /dev/virtio-ports/ovirt-guest-agent.0:/dev/virtio-ports/ovirt-guest-agent.0
    - /dev/virtio-ports/org.qemu.guest_agent.0:/dev/virtio-ports/org.qemu.guest_agent.0
    tty: true
